version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    image: so000000/atcoder:dev

    volumes:
      - ../problems:/root/problems:cached
      - ../library:/root/library:cached
      - ../.vscode:/root/.vscode:cached

      - ../dotfiles/.zshrc:/root/.zshrc
      - ../dotfiles/.zinit:/root/.zinit
      - ../dotfiles/.zsh_history:/root/.zsh_history
      - ../dotfiles/.aliases:/root/.aliases

    command: /bin/sh -c 'while sleep 1000; do :; done'
